### ISSUE TITLE
build-country-sets.sh not working any more due GeoLite Legacy databases were discontinued on January 2, 2019

### ISSUE THREAD

**Issue by ambergerit** [chr0mag/geoipsets#1]
GeoLite Legacy databases were discontinued on January 2, 2019, so the downloadlink isn't working any more and script fails. 

The new database format could be downloaded here:
https://legacy-geoip-csv.ufficyo.com/Legacy-MaxMind-GeoIP-database.tar.gz

Or the new possibility for using the free-maxmind account need's to be implemented

but Script needs to be changed to use this file.

**Comment by chr0mag** [comment]
@ambergerit - thanks for the heads up. The v1.1 release fixes this.
