### ISSUE TITLE
feature request: include external country list file

### ISSUE THREAD

**Issue by pgnd** [chr0mag/geoipsets#6]
i've a local list of countries to be geoip-handled that's used by a number of other tools/utilities.

it's of a simple txt-file format: e.g.

```
#AD   # Andorra
AE    # United_Arab_Emirates
AF    # Afghanistan
#AG   # Antigua_and_Barbuda
...
```

it would be quite convenient for geoipsets' config to be able to **_include_** the already-existing external country list, as an option/alternative to listing the targeted countries withing the /etc/geoipsets.conf file.

not sure how to best handle such an option for both the bash- & python-utility cases.

**Comment by chr0mag** [comment]
Thanks for the request @pgnd . One way to handle this would be to add command line options (eg. `--firewall`, `--ip-version`, `--countries`...) that override what is in `/etc/geoipsets.conf`. The `--countries` flag could accept a text file in the format you described (list of 2-char country codes, one per line). Thoughts?

The Bash version of this is effectively legacy at this point. It always outputs all the sets for both firewalls without option. I don't have any plans to make any changes to this.

**Comment by pgnd** [comment]
hi @chr0mag 

cmd line opts should do the trick.

the python version is what i'm using atm; works great.   i just wanted to avoid suggesting a solution that worked only with one, not the other.  but if you're moving to python-only, sounds good to me.

as for the format "list of 2-char country codes, one per line", personally I'd allow comments in the file ... both at the beginning of the line, which the parser would ignore the entire line -- and enabling the country -- as well as comments at the end of a line.  like in my example above.

**Comment by chr0mag** [comment]
@pgnd -- This is now possible with the latest v2.2.5 release.
